# Generated by Django 4.1.4 on 2022-12-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image_url', models.URLField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('tags', models.CharField(max_length=100, null=True)),
                ('github_url', models.URLField(max_length=500)),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
