# Generated by Django 4.1.4 on 2022-12-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.URLField(max_length=5000),
        ),
    ]
