# Generated by Django 4.1.4 on 2022-12-11 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_visitor'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='visitor',
            table='visitor',
        ),
    ]
