# Generated by Django 4.1.4 on 2022-12-11 06:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_visitor_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='visit_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
