# Generated by Django 4.1.4 on 2022-12-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_visitor_visit_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='visit_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
